CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE TABLE roles (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),name varchar(50) NOT NULL UNIQUE,description varchar(500),created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE permissions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),name varchar(100) NOT NULL UNIQUE,description varchar(500),created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE role_permissions (role_id uuid NOT NULL REFERENCES roles(id) ON DELETE CASCADE,permission_id uuid NOT NULL REFERENCES permissions(id) ON DELETE CASCADE,created_at timestamptz NOT NULL DEFAULT now(),PRIMARY KEY(role_id,permission_id));
CREATE TABLE administrators (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),role_id uuid NOT NULL REFERENCES roles(id) ON DELETE RESTRICT,name varchar(150) NOT NULL,email varchar(254) NOT NULL,email_normalized varchar(254) NOT NULL UNIQUE,password_hash varchar(255) NOT NULL,is_active boolean NOT NULL DEFAULT true,failed_login_count integer NOT NULL DEFAULT 0,locked_until timestamptz,last_login_at timestamptz,deleted_at timestamptz,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),CONSTRAINT administrators_failed_login_nonnegative CHECK(failed_login_count>=0));
CREATE TABLE sessions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),administrator_id uuid NOT NULL REFERENCES administrators(id) ON DELETE CASCADE,token_hash varchar(64) NOT NULL UNIQUE,csrf_token_hash varchar(64) NOT NULL,ip_address varchar(45),user_agent varchar(500),last_seen_at timestamptz NOT NULL DEFAULT now(),expires_at timestamptz NOT NULL,absolute_expires_at timestamptz NOT NULL,revoked_at timestamptz,revoke_reason varchar(100),created_at timestamptz NOT NULL DEFAULT now(),CONSTRAINT sessions_expiry_order CHECK(expires_at<=absolute_expires_at),CONSTRAINT sessions_revoked_order CHECK(revoked_at IS NULL OR revoked_at>=created_at));
CREATE TABLE audit_logs (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),administrator_id uuid REFERENCES administrators(id) ON DELETE SET NULL,request_id uuid NOT NULL,action varchar(100) NOT NULL,success boolean NOT NULL,failure_reason_code varchar(100),entity_type varchar(100),entity_id uuid,ip_address varchar(45),user_agent varchar(500),metadata jsonb NOT NULL DEFAULT '{}'::jsonb,created_at timestamptz NOT NULL DEFAULT now(),CONSTRAINT audit_metadata_object CHECK(jsonb_typeof(metadata)='object'));
CREATE TABLE rate_limits (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),scope varchar(50) NOT NULL,key_hash varchar(64) NOT NULL,window_started_at timestamptz NOT NULL,attempt_count integer NOT NULL DEFAULT 1,expires_at timestamptz NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),CONSTRAINT rate_limits_window_unique UNIQUE(scope,key_hash,window_started_at),CONSTRAINT rate_limits_attempt_positive CHECK(attempt_count>=1),CONSTRAINT rate_limits_expiry_order CHECK(expires_at>window_started_at));
CREATE INDEX administrators_role_id_idx ON administrators(role_id); CREATE INDEX administrators_active_idx ON administrators(is_active) WHERE deleted_at IS NULL; CREATE INDEX sessions_administrator_idx ON sessions(administrator_id); CREATE INDEX sessions_absolute_active_idx ON sessions(absolute_expires_at) WHERE revoked_at IS NULL; CREATE INDEX audit_request_id_idx ON audit_logs(request_id); CREATE INDEX audit_administrator_idx ON audit_logs(administrator_id); CREATE INDEX audit_created_at_idx ON audit_logs(created_at); CREATE INDEX rate_limits_scope_key_idx ON rate_limits(scope,key_hash); CREATE INDEX rate_limits_expires_idx ON rate_limits(expires_at);
