import { useEffect, useState, type FormEvent } from "react";
import { apiFetch, ApiError } from "../lib/api-client";
import { Button, Card, EmptyState } from "./ui";
import { formatMxn, parseMxnToCents } from "./WorkshopServices";

interface Summary { totalCents: number; paidCents: number; discountCents: number; creditAppliedCents: number; pendingCents: number; favorCents: number; paymentStatus: string }
interface Movement { id: string; type: string; amountCents: number; paymentMethod: string | null; reference: string | null; note: string | null; occurredDate: string; correctedMovementId: string | null; createdAt: string }
interface AgreementRow { agreement: { id: string; discountType: "percentage" | "fixed"; value: number; validFrom: string; validUntil: string | null; active: boolean }; team: { name: string } }
interface OrderOption { id: string; orderNumber: string; customerId: string }
const currentDate = () => new Date().toISOString().slice(0, 10);
const typeNames: Record<string, string> = { advance: "Anticipo", payment: "Pago", discount: "Descuento", credit_applied: "Favor aplicado", charge: "Cargo", refund: "Reembolso", correction: "Reversión" };
const methodNames: Record<string, string> = { cash: "Efectivo", card: "Tarjeta", transfer: "Transferencia", customer_credit: "Saldo a favor", agreement: "Convenio", other: "Otro" };

export function WorkshopFinancials({ order, orders, permissions }: { order: OrderOption; orders: OrderOption[]; permissions: string[] }) {
  const canView = permissions.includes("view_workshop_financials");
  const canManage = permissions.includes("manage_workshop_financials");
  const canApplyAgreement = permissions.includes("manage_workshop_agreements");
  const [data, setData] = useState<{ summary: Summary | null; movements: Movement[] } | null>(null);
  const [agreements, setAgreements] = useState<AgreementRow[]>([]);
  const [form, setForm] = useState({ type: "payment", amount: "", paymentMethod: "cash", reference: "", note: "", occurredDate: currentDate() });
  const [favor, setFavor] = useState({ targetOrderId: "", amount: "", note: "", occurredDate: currentDate() });
  const [refund, setRefund] = useState({ amount: "", paymentMethod: "cash", reference: "", reason: "", occurredDate: currentDate() });
  const [agreementId, setAgreementId] = useState("");
  const [notice, setNotice] = useState("");
  const load = async () => { try { setData(await apiFetch(`/api/admin/workshop/orders/${order.id}/movements`)); } catch (error) { setNotice(error instanceof ApiError ? error.message : "No fue posible cargar movimientos."); } };
  useEffect(() => { if (canView) void load(); }, [order.id, canView]);
  useEffect(() => { if (canApplyAgreement) apiFetch<AgreementRow[]>("/api/admin/workshop/agreements").then(setAgreements).catch(() => setAgreements([])); }, [canApplyAgreement]);
  async function mutate(path: string, body: unknown) { try { await apiFetch(path, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(body) }); setNotice("Movimiento registrado."); await load(); } catch (error) { setNotice(error instanceof ApiError ? error.message : "No fue posible registrar el movimiento."); } }
  async function add(event: FormEvent) { event.preventDefault(); const amountCents = parseMxnToCents(form.amount); if (!amountCents) return setNotice("Captura un monto válido."); await mutate(`/api/admin/workshop/orders/${order.id}/movements`, { type: form.type, amountCents, paymentMethod: form.type === "discount" || form.type === "charge" ? null : form.paymentMethod, reference: form.reference || null, note: form.note || null, occurredDate: form.occurredDate }); setForm({ ...form, amount: "", reference: "", note: "" }); }
  async function reverse(movement: Movement) { const reason = prompt("Motivo obligatorio de la reversión:")?.trim(); if (reason) await mutate(`/api/admin/workshop/movements/${movement.id}/reverse`, { reason }); }
  const reversedIds = new Set(data?.movements.filter((movement) => movement.correctedMovementId).map((movement) => movement.correctedMovementId) ?? []);
  const targets = orders.filter((candidate) => candidate.customerId === order.customerId && candidate.id !== order.id);
  const applicableAgreements = agreements.filter(({ agreement }) => agreement.validFrom <= currentDate() && (!agreement.validUntil || agreement.validUntil >= currentDate()));
  if (!canView) return <EmptyState title="Costos restringidos" description="No tienes permiso para consultar información financiera." />;
  return <section className="workshop-finance">
    {notice && <p role="status" className="form-error">{notice}</p>}
    {data?.summary && <dl className="finance-summary">{[["Total", data.summary.totalCents], ["Pagado", data.summary.paidCents], ["Descuento", data.summary.discountCents], ["Crédito aplicado", data.summary.creditAppliedCents], ["Pendiente", data.summary.pendingCents], ["A favor", data.summary.favorCents]].map(([label, value]) => <div key={String(label)}><dt>{label}</dt><dd>{formatMxn(Number(value))}</dd></div>)}</dl>}
    {canManage && <Card className="finance-form"><h3>Registrar movimiento</h3><form onSubmit={add}><div className="finance-fields"><label>Tipo<select value={form.type} onChange={(event) => setForm({ ...form, type: event.target.value })}><option value="advance">Anticipo</option><option value="payment">Pago</option><option value="discount">Descuento</option><option value="charge">Cargo</option></select></label><label>Monto (MXN)<input required inputMode="decimal" value={form.amount} onChange={(event) => setForm({ ...form, amount: event.target.value })} /></label>{!["discount", "charge"].includes(form.type) && <label>Método<select value={form.paymentMethod} onChange={(event) => setForm({ ...form, paymentMethod: event.target.value })}><option value="cash">Efectivo</option><option value="card">Tarjeta</option><option value="transfer">Transferencia</option><option value="other">Otro</option></select></label>}<label>Fecha<input required type="date" value={form.occurredDate} onChange={(event) => setForm({ ...form, occurredDate: event.target.value })} /></label><label>Referencia<input value={form.reference} onChange={(event) => setForm({ ...form, reference: event.target.value })} /></label><label>Nota<input required={form.paymentMethod === "other"} value={form.note} onChange={(event) => setForm({ ...form, note: event.target.value })} /></label></div><Button>Registrar</Button></form></Card>}
    {(canManage || canApplyAgreement) && <div className="finance-actions">
      {canApplyAgreement && <Card><h3>Aplicar convenio válido</h3><label>Convenio<select value={agreementId} onChange={(event) => setAgreementId(event.target.value)}><option value="">Selecciona</option>{applicableAgreements.map(({ agreement, team }) => <option key={agreement.id} value={agreement.id}>{team.name} · {agreement.discountType === "percentage" ? `${agreement.value / 100}%` : formatMxn(agreement.value)}</option>)}</select></label>{!applicableAgreements.length && <small>No hay convenios vigentes. La afiliación del cliente también se valida al aplicar.</small>}<Button type="button" disabled={!agreementId} onClick={() => void mutate(`/api/admin/workshop/orders/${order.id}/agreement`, { agreementId, occurredDate: currentDate() })}>Aplicar convenio</Button></Card>}
      {canManage && data?.summary && data.summary.favorCents > 0 && <><Card><h3>Aplicar favor a otra orden</h3><label>Orden destino<select value={favor.targetOrderId} onChange={(event) => setFavor({ ...favor, targetOrderId: event.target.value })}><option value="">Selecciona</option>{targets.map((target) => <option key={target.id} value={target.id}>{target.orderNumber}</option>)}</select></label><label>Monto (MXN)<input inputMode="decimal" value={favor.amount} onChange={(event) => setFavor({ ...favor, amount: event.target.value })} /></label><label>Nota<input value={favor.note} onChange={(event) => setFavor({ ...favor, note: event.target.value })} /></label><Button type="button" disabled={!favor.targetOrderId || !favor.amount} onClick={() => { const amountCents = parseMxnToCents(favor.amount); if (amountCents) void mutate(`/api/admin/workshop/orders/${order.id}/apply-favor`, { targetOrderId: favor.targetOrderId, amountCents, occurredDate: favor.occurredDate, note: favor.note || null }); }}>Aplicar favor</Button></Card><Card><h3>Reembolsar favor</h3><label>Monto (MXN)<input inputMode="decimal" value={refund.amount} onChange={(event) => setRefund({ ...refund, amount: event.target.value })} /></label><label>Método<select value={refund.paymentMethod} onChange={(event) => setRefund({ ...refund, paymentMethod: event.target.value })}><option value="cash">Efectivo</option><option value="card">Tarjeta</option><option value="transfer">Transferencia</option><option value="other">Otro</option></select></label><label>Referencia<input value={refund.reference} onChange={(event) => setRefund({ ...refund, reference: event.target.value })} /></label><label>Motivo<input required value={refund.reason} onChange={(event) => setRefund({ ...refund, reason: event.target.value })} /></label><Button type="button" disabled={!refund.amount || !refund.reason.trim()} onClick={() => { const amountCents = parseMxnToCents(refund.amount); if (amountCents) void mutate(`/api/admin/workshop/orders/${order.id}/refund-favor`, { amountCents, paymentMethod: refund.paymentMethod, reference: refund.reference || null, reason: refund.reason, occurredDate: refund.occurredDate }); }}>Reembolsar</Button></Card></>}
    </div>}
    <section className="finance-history"><h3>Historial inmutable</h3>{data?.movements.length ? <div className="finance-movements">{data.movements.map((movement) => <article key={movement.id}><div><strong>{typeNames[movement.type] ?? movement.type}</strong><small>{movement.occurredDate} · {methodNames[movement.paymentMethod ?? ""] ?? "Sin método"}</small>{(movement.reference || movement.note) && <small>{[movement.reference, movement.note].filter(Boolean).join(" · ")}</small>}</div><b className={movement.amountCents < 0 ? "is-negative" : ""}>{formatMxn(movement.amountCents)}</b>{canManage && movement.type !== "correction" && !reversedIds.has(movement.id) && <button type="button" onClick={() => void reverse(movement)}>Revertir completo</button>}</article>)}</div> : <EmptyState title="Sin movimientos" description="Los movimientos financieros aparecerán aquí sin poder editarse ni eliminarse." />}</section>
  </section>;
}
