import { useEffect, useRef, useState, type FormEvent, type ReactNode } from "react";
import { Button, Input, Select, Textarea } from "./ui";
import { BICYCLE_BRANDS, BICYCLE_COLORS, BICYCLE_CONDITIONS, BICYCLE_TYPES, BRAKE_TYPES, DRIVETRAINS, SUSPENSION_TYPES, WHEEL_SIZES } from "../lib/bicycle-catalogs";
import { EMPTY_WORKSHOP_REQUEST, getWorkshopAvailability, getWorkshopCatalog, type WorkshopAvailability, type WorkshopCatalogService, type WorkshopRequestDraft } from "../lib/workshop-request";
import { isValidMexicanPhone } from "../lib/mexican-phone";

type BicycleOption = { id: string; label: string };
const STEPS = ["Tus datos", "Tu bicicleta", "Servicio", "Fecha y horario", "Revisión y envío"];
const STORAGE_KEY = "mibicla:workshop-request-draft";

function Field({ label, children }: { label: string; children: ReactNode }) { return <label><span>{label}</span>{children}</label>; }
function CatalogSelect({ label, value, options, onChange }: { label: string; value: string; options: string[]; onChange: (value: string) => void }) {
  const other = value && !options.includes(value);
  return <Field label={label}><Select value={other ? "__other" : value} onChange={(event) => onChange(event.target.value === "__other" ? "Otro" : event.target.value)}><option value="">Selecciona</option>{options.map((option) => <option key={option}>{option}</option>)}<option value="__other">Otro</option></Select>{other && <Input aria-label={`${label}, otro`} value={value === "Otro" ? "" : value} onChange={(event) => onChange(event.target.value)} placeholder={`Especifica ${label.toLowerCase()}`} />}</Field>;
}

export function WorkshopRequestFlow({ initial, bicycles = [], authenticated = false, onSubmit, onCancel }: {
  initial?: Partial<WorkshopRequestDraft>; bicycles?: BicycleOption[]; authenticated?: boolean;
  onSubmit: (draft: WorkshopRequestDraft) => Promise<void>; onCancel?: () => void;
}) {
  const [draft, setDraft] = useState<WorkshopRequestDraft>(() => {
    if (!authenticated) try { return { ...EMPTY_WORKSHOP_REQUEST, ...JSON.parse(sessionStorage.getItem(STORAGE_KEY) || "{}"), ...initial }; } catch { /* ignore invalid local draft */ }
    return { ...EMPTY_WORKSHOP_REQUEST, ...initial };
  });
  const [step, setStep] = useState(authenticated ? 1 : 0), [catalog, setCatalog] = useState<WorkshopCatalogService[]>([]);
  const [availability, setAvailability] = useState<WorkshopAvailability | null>(null), [error, setError] = useState("");
  const [busy, setBusy] = useState(false); const heading = useRef<HTMLHeadingElement>(null);
  const set = <K extends keyof WorkshopRequestDraft>(key: K, value: WorkshopRequestDraft[K]) => setDraft((current) => ({ ...current, [key]: value }));
  useEffect(() => { void Promise.all([getWorkshopCatalog(), getWorkshopAvailability()]).then(([services, schedule]) => { setCatalog(services); setAvailability(schedule); const requested = initial?.serviceName?.toLocaleLowerCase("es-MX"); const match = services.find((item) => item.name.toLocaleLowerCase("es-MX") === requested); setDraft((current) => requested ? ({ ...current, catalogServiceId: match?.id ?? "", serviceName: match?.name ?? "Otro / necesito diagnóstico" }) : current); }); }, []);
  useEffect(() => { if (!authenticated) sessionStorage.setItem(STORAGE_KEY, JSON.stringify(draft)); }, [authenticated, draft]);
  useEffect(() => { heading.current?.focus(); }, [step]);
  useEffect(() => { const warn = (event: BeforeUnloadEvent) => { if (JSON.stringify(draft) !== JSON.stringify(EMPTY_WORKSHOP_REQUEST)) event.preventDefault(); }; window.addEventListener("beforeunload", warn); return () => window.removeEventListener("beforeunload", warn); }, [draft]);
  function next() {
    const invalid = step === 0 ? (!draft.customerName.trim() || !isValidMexicanPhone(draft.customerPhone) || (draft.customerEmail && !/^\S+@\S+\.\S+$/.test(draft.customerEmail)))
      : step === 1 ? (authenticated ? !draft.bicycleId : !draft.bikeBrand || !draft.bikeType)
        : step === 2 ? (!draft.serviceName || draft.problemDescription.trim().length < 10)
          : step === 3 ? Boolean(availability?.configured && (!draft.requestedDate || !draft.requestedTime)) : false;
    if (invalid) { setError("Completa los campos requeridos de este paso."); return; }
    setError(""); setStep((current) => Math.min(4, current + 1));
  }
  async function submit(event: FormEvent) { event.preventDefault(); setBusy(true); setError(""); try { await onSubmit(draft); if (!authenticated) sessionStorage.removeItem(STORAGE_KEY); } catch { setError("No fue posible enviar la solicitud. Revisa los datos e inténtalo nuevamente."); } finally { setBusy(false); } }
  const selectedDay = availability?.days.find((day) => day.date === draft.requestedDate);
  return <form className="workshop-flow" onSubmit={submit}>
    <ol className="workshop-flow-progress" aria-label="Progreso">{STEPS.map((label, index) => <li className={index === step ? "is-current" : index < step ? "is-complete" : ""} key={label}><span>{index + 1}</span><small>{label}</small></li>)}</ol>
    <section className="workshop-flow-step"><h2 ref={heading} tabIndex={-1}>{STEPS[step]}</h2>
      {step === 0 && <div className="workshop-flow-grid"><Field label="Nombre completo *"><Input required value={draft.customerName} onChange={(e) => set("customerName", e.target.value)} /></Field><Field label="Teléfono *"><Input required type="tel" inputMode="tel" value={draft.customerPhone} onChange={(e) => set("customerPhone", e.target.value)} /></Field><Field label="Correo opcional"><Input type="email" value={draft.customerEmail} onChange={(e) => set("customerEmail", e.target.value)} /></Field><Field label="Contacto preferido"><Select value={draft.preferredContactMethod} onChange={(e) => set("preferredContactMethod", e.target.value as WorkshopRequestDraft["preferredContactMethod"])}><option value="whatsapp">WhatsApp</option><option value="phone">Llamada</option><option value="email">Correo</option></Select></Field><p className="workshop-flow-note">Si ya tienes cuenta, puedes iniciar sesión para usar tus bicicletas guardadas. Por seguridad, no vincularemos datos sin autenticarte.</p></div>}
      {step === 1 && <div className="workshop-flow-grid">{authenticated && <Field label="Bicicleta guardada *"><Select required value={draft.bicycleId} onChange={(e) => set("bicycleId", e.target.value)}><option value="">Selecciona</option>{bicycles.map((bike) => <option value={bike.id} key={bike.id}>{bike.label}</option>)}</Select></Field>}{!authenticated && <><CatalogSelect label="Marca" value={draft.bikeBrand} options={BICYCLE_BRANDS} onChange={(v) => set("bikeBrand", v)} /><Field label="Modelo"><Input value={draft.bikeModel} onChange={(e) => set("bikeModel", e.target.value)} /></Field><CatalogSelect label="Tipo" value={draft.bikeType} options={BICYCLE_TYPES} onChange={(v) => set("bikeType", v)} /><CatalogSelect label="Color" value={draft.bikeColor} options={BICYCLE_COLORS} onChange={(v) => set("bikeColor", v)} /><CatalogSelect label="Rodada" value={draft.bikeWheelSize} options={WHEEL_SIZES} onChange={(v) => set("bikeWheelSize", v)} /><Field label="Año"><Input type="number" min="1900" max="2100" value={draft.bikeYear} onChange={(e) => set("bikeYear", e.target.value)} /></Field><CatalogSelect label="Frenos" value={draft.bikeBrakeType} options={BRAKE_TYPES} onChange={(v) => set("bikeBrakeType", v)} /><CatalogSelect label="Suspensión" value={draft.bikeSuspensionType} options={SUSPENSION_TYPES} onChange={(v) => set("bikeSuspensionType", v)} /><CatalogSelect label="Transmisión" value={draft.bikeDrivetrain} options={DRIVETRAINS} onChange={(v) => set("bikeDrivetrain", v)} /><CatalogSelect label="Condición general" value={draft.bikeGeneralCondition} options={BICYCLE_CONDITIONS} onChange={(v) => set("bikeGeneralCondition", v)} /><Field label="Número de serie"><Input value={draft.bikeSerialNumber} onChange={(e) => set("bikeSerialNumber", e.target.value)} /></Field><Field label="Número de cuadro"><Input value={draft.bikeFrameNumber} onChange={(e) => set("bikeFrameNumber", e.target.value)} /></Field><Field label="Notas"><Textarea value={draft.bikeNotes} onChange={(e) => set("bikeNotes", e.target.value)} /></Field><Field label="Accesorios entregados"><Textarea value={draft.bikeAccessories} onChange={(e) => set("bikeAccessories", e.target.value)} /></Field></>}</div>}
      {step === 2 && <div className="workshop-flow-grid"><Field label="Servicio principal *"><Select required value={draft.catalogServiceId || "other"} onChange={(e) => { const service = catalog.find((item) => item.id === e.target.value); set("catalogServiceId", service?.id ?? ""); set("serviceName", service?.name ?? "Otro / necesito diagnóstico"); }}><option value="other">Otro / necesito diagnóstico</option>{catalog.map((service) => <option value={service.id} key={service.id}>{service.name}</option>)}</Select></Field><Field label="Descripción del problema *"><Textarea required minLength={10} value={draft.problemDescription} onChange={(e) => set("problemDescription", e.target.value)} /></Field><Field label="Síntomas o ruidos"><Textarea value={draft.symptoms} onChange={(e) => set("symptoms", e.target.value)} /></Field><Field label="Daños visibles"><Textarea value={draft.visibleDamage} onChange={(e) => set("visibleDamage", e.target.value)} /></Field><Field label="Comentarios adicionales"><Textarea value={draft.additionalComments} onChange={(e) => set("additionalComments", e.target.value)} /></Field></div>}
      {step === 3 && <div className="workshop-flow-grid"><p className="workshop-flow-note">Esta solicitud no confirma una cita. El taller revisará la disponibilidad y te enviará una confirmación.</p>{availability?.configured ? <><Field label="Día para dejar la bicicleta *"><Select required value={draft.requestedDate} onChange={(e) => { set("requestedDate", e.target.value); set("requestedTime", ""); }}><option value="">Selecciona</option>{availability.days.filter((day) => day.available).map((day) => <option value={day.date} key={day.date}>{new Date(`${day.date}T12:00:00`).toLocaleDateString("es-MX", { dateStyle: "long" })}</option>)}</Select></Field><Field label="Horario preferido *"><Select required value={draft.requestedTime} onChange={(e) => set("requestedTime", e.target.value)}><option value="">Selecciona</option>{selectedDay?.times.map((time) => <option key={time}>{time}</option>)}</Select></Field></> : <p>No hay una agenda configurada. Puedes enviar la solicitud sin fecha y el taller acordará contigo la recepción.</p>}<Field label="Entrega deseada (no es promesa)"><Input type="date" min={new Date().toISOString().slice(0, 10)} value={draft.desiredDeliveryDate} onChange={(e) => set("desiredDeliveryDate", e.target.value)} /></Field><Field label="Urgencia"><Select value={draft.urgency} onChange={(e) => set("urgency", e.target.value as WorkshopRequestDraft["urgency"])}><option value="normal">Normal</option><option value="soon">Lo antes posible</option><option value="urgent">Urgente</option></Select></Field></div>}
      {step === 4 && <div className="workshop-flow-review"><section><h3>Contacto</h3><p>{authenticated ? "Datos de tu cuenta" : `${draft.customerName} · ${draft.customerPhone}`}</p><button type="button" onClick={() => setStep(0)}>Editar</button></section><section><h3>Bicicleta</h3><p>{authenticated ? bicycles.find((bike) => bike.id === draft.bicycleId)?.label : [draft.bikeBrand, draft.bikeModel, draft.bikeType].filter(Boolean).join(" · ")}</p><button type="button" onClick={() => setStep(1)}>Editar</button></section><section><h3>Servicio</h3><p>{draft.serviceName}</p><p>{draft.problemDescription}</p><button type="button" onClick={() => setStep(2)}>Editar</button></section><section><h3>Fecha preferida</h3><p>{draft.requestedDate ? `${draft.requestedDate} · ${draft.requestedTime}` : "Por acordar con el taller"}</p><button type="button" onClick={() => setStep(3)}>Editar</button></section><p className="workshop-flow-note">La solicitud queda pendiente de revisión y no representa una orden ni una cita confirmada.</p></div>}
      {error && <p className="form-error" role="alert">{error}</p>}
    </section>
    <footer className="workshop-flow-actions">{onCancel && <Button type="button" variant="ghost" onClick={onCancel}>Cancelar</Button>}{step > (authenticated ? 1 : 0) && <Button type="button" variant="secondary" onClick={() => setStep((current) => current - 1)}>Anterior</Button>}{step < 4 ? <Button type="button" onClick={next}>Continuar</Button> : <Button disabled={busy}>{busy ? "Enviando…" : "Enviar solicitud"}</Button>}</footer>
  </form>;
}
