export const ROLE_NAMES = ["owner", "admin", "employee"] as const;
export type RoleName = (typeof ROLE_NAMES)[number];

export const PERMISSION_NAMES = [
  "manage_employees",
  "manage_roles",
  "manage_settings",
  "manage_products",
  "manage_promotions",
  "manage_events",
  "manage_catalog_requests",
  "manage_services",
  "manage_customers",
  "view_customers",
  "create_customers",
  "register_purchase",
  "register_service",
  "redeem_reward",
  "reverse_movement",
  "view_audit_logs",
  "view_reports",
  "view_business_settings",
  "manage_business_settings",
  "view_deposit_settings",
  "manage_deposit_settings",
  "view_loyalty",
  "manage_loyalty",
  "assign_rewards",
  "adjust_loyalty",
  "view_bicycles",
  "manage_bicycles",
  "view_workshop_requests",
  "manage_workshop_requests",
  "view_workshop_orders",
  "create_workshop_orders",
  "update_workshop_orders",
  "manage_workshop_services",
  "manage_workshop_parts",
  "manage_workshop_status",
  "publish_workshop_updates",
  "notify_workshop_customers",
  "view_workshop_financials",
  "manage_workshop_financials",
  "manage_workshop_pricing",
  "manage_workshop_agreements",
  "manage_customer_financing",
  "manage_workshop_settings",
] as const;
export type PermissionName = (typeof PERMISSION_NAMES)[number];

export const ROLE_PERMISSIONS: Record<RoleName, readonly PermissionName[]> = {
  owner: PERMISSION_NAMES,
  admin: [
    "manage_products",
    "manage_promotions",
    "manage_events",
    "manage_catalog_requests",
    "manage_services",
    "manage_customers",
    "view_customers",
    "create_customers",
    "register_purchase",
    "register_service",
    "redeem_reward",
    "reverse_movement",
    "view_reports",
    "view_business_settings",
    "manage_business_settings",
    "view_deposit_settings",
    "manage_deposit_settings",
    "view_loyalty",
    "manage_loyalty",
    "assign_rewards",
    "adjust_loyalty",
    "view_bicycles",
    "manage_bicycles",
    "view_workshop_requests",
    "manage_workshop_requests",
    "view_workshop_orders",
    "create_workshop_orders",
    "update_workshop_orders",
    "manage_workshop_services",
    "manage_workshop_parts",
    "manage_workshop_status",
    "publish_workshop_updates",
    "notify_workshop_customers",
    "view_workshop_financials",
    "manage_workshop_financials",
    "manage_workshop_pricing",
    "manage_workshop_agreements",
    "manage_customer_financing",
    "manage_workshop_settings",
  ],
  employee: [
    "view_customers",
    "create_customers",
    "register_purchase",
    "register_service",
    "redeem_reward",
    "view_bicycles",
    "manage_bicycles",
    "view_workshop_requests",
    "manage_workshop_requests",
    "view_workshop_orders",
    "create_workshop_orders",
    "update_workshop_orders",
    "manage_workshop_services",
    "manage_workshop_parts",
    "manage_workshop_status",
    "publish_workshop_updates",
    "notify_workshop_customers",
  ],
};

export const SESSION_IDLE_MS = 30 * 60 * 1000;
export const SESSION_ABSOLUTE_MS = 8 * 60 * 60 * 1000;
export const SESSION_TOUCH_MS = 5 * 60 * 1000;
export const LOGIN_WINDOW_MS = 15 * 60 * 1000;
export const LOGIN_MAX_ATTEMPTS = 5;
export const ACCOUNT_LOCK_ATTEMPTS = 5;
export const ACCOUNT_LOCK_MS = 15 * 60 * 1000;
export const MAX_AUDIT_METADATA_BYTES = 8_192;
